//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alberlan.eCredito.UI.WF.Servico.CalculoFinanciamento.Financiamento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.CalculoFinanciamento.Financiamento.IFinanciamento")]
    public interface IFinanciamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/Consultar", ReplyAction="http://tempuri.org/IFinanciamento/ConsultarResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/Incluir", ReplyAction="http://tempuri.org/IFinanciamento/IncluirResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Incluir(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/Editar", ReplyAction="http://tempuri.org/IFinanciamento/EditarResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Editar(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/Excluir", ReplyAction="http://tempuri.org/IFinanciamento/ExcluirResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Excluir(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/IncluirTodos", ReplyAction="http://tempuri.org/IFinanciamento/IncluirTodosResponse")]
        void IncluirTodos(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] financiamentosDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/Verificar", ReplyAction="http://tempuri.org/IFinanciamento/VerificarResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.ValidacaoDTO[] Verificar(double valorSolicitado, int qdtParcela, System.DateTime dtaPrimeiroVencto, int tipoFinanciamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/SolicitarFinanciamento", ReplyAction="http://tempuri.org/IFinanciamento/SolicitarFinanciamentoResponse")]
        Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.CalculoFinanciamentoDTO SolicitarFinanciamento(int codCliente, int tipoFinanciamento, double valorSolicitado, int qdtParcela, System.DateTime dtaPrimeiroVencto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanciamento/ConfirmarFinanciamento", ReplyAction="http://tempuri.org/IFinanciamento/ConfirmarFinanciamentoResponse")]
        bool ConfirmarFinanciamento(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.CalculoFinanciamentoDTO calculoFinanciamentoDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanciamentoChannel : Alberlan.eCredito.UI.WF.Servico.CalculoFinanciamento.Financiamento.IFinanciamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanciamentoClient : System.ServiceModel.ClientBase<Alberlan.eCredito.UI.WF.Servico.CalculoFinanciamento.Financiamento.IFinanciamento>, Alberlan.eCredito.UI.WF.Servico.CalculoFinanciamento.Financiamento.IFinanciamento {
        
        public FinanciamentoClient() {
        }
        
        public FinanciamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanciamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanciamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanciamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Incluir(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO) {
            return base.Channel.Incluir(financiamentoDTO);
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Editar(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO) {
            return base.Channel.Editar(financiamentoDTO);
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] Excluir(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO financiamentoDTO) {
            return base.Channel.Excluir(financiamentoDTO);
        }
        
        public void IncluirTodos(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.FinanciamentoDTO[] financiamentosDTO) {
            base.Channel.IncluirTodos(financiamentosDTO);
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.ValidacaoDTO[] Verificar(double valorSolicitado, int qdtParcela, System.DateTime dtaPrimeiroVencto, int tipoFinanciamento) {
            return base.Channel.Verificar(valorSolicitado, qdtParcela, dtaPrimeiroVencto, tipoFinanciamento);
        }
        
        public Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.CalculoFinanciamentoDTO SolicitarFinanciamento(int codCliente, int tipoFinanciamento, double valorSolicitado, int qdtParcela, System.DateTime dtaPrimeiroVencto) {
            return base.Channel.SolicitarFinanciamento(codCliente, tipoFinanciamento, valorSolicitado, qdtParcela, dtaPrimeiroVencto);
        }
        
        public bool ConfirmarFinanciamento(Alberlan.eCredito.Interface.DTO.CalculoFinanciamento.CalculoFinanciamentoDTO calculoFinanciamentoDTO) {
            return base.Channel.ConfirmarFinanciamento(calculoFinanciamentoDTO);
        }
    }
}
